### ISSUE TITLE
Access Request Failed

### ISSUE THREAD

**Issue by stevesong** [FiloSottile/tripit-to-flightdiary#2]
Hi,

Followed the instructions, got the developer keys and inserted it into creds.json.  But when I click on the link, TripIt reports Access Request Failed.  I've double checked the keys and they are entered correctly.

```
python get_token.py 
{u'oauth_token_secret': u'XXXXXXXXXXXXXXXXXXXXXXXXX', u'oauth_token': u'YYYYYYYYYYYYYYYYY'}
https://www.tripit.com/oauth/authorize?oauth_token=ZZZZZZZZZZZZZZZZZZ&oauth_callback=foo
```

Pressing return after this produces:

```
Traceback (most recent call last):
  File "get_token.py", line 16, in <module>
    oauth_response = oauth.parse_authorization_response(raw_input())
  File "/usr/local/lib/python2.7/dist-packages/requests_oauthlib/oauth1_session.py", line 328, in parse_authorization_response
    self._populate_attributes(token)
  File "/usr/local/lib/python2.7/dist-packages/requests_oauthlib/oauth1_session.py", line 337, in _populate_attributes
    token,
requests_oauthlib.oauth1_session.TokenMissing: Response does not contain a token: {}
```

Am I missing something obvious?   

P.S.  Adding `pip install requests requests_oauthlib` to the installation instructions would help the pythonly-challenged like me.

**Comment by smnlng** [comment]
I have the same issue. I copied and pasted the entire URL (https://www.tripit.com/oauth/authorize?oauth_token=ZZZZZZZZZZZZZZZZZZ&oauth_callback=foo) back into the shell and I did get a prompt, but got the following: 
TokenRequestDenied: Token request failed with code 401, response was '<Response><Error><code>401</code><detailed_error_code>106.300000</detailed_error_code><description>attempted to fetch an access token with an unauthorized request token</description></Error></Response>'.

In my case, the oauth_token YYYYYYYYYYYYYYYYY and the pasting of the URL (ZZZZZZZZZZZZZZZZZZZZ in your example) are the same.

**Comment by RubenVerborgh** [comment]
Same problem. Any update on this, @FiloSottile?

**Comment by estesp** [comment]
The API seems to no longer like a specified callback that doesn't conform to a URL; modifying "foo" to "http://localhost/foo" caused the script to work again for me.

**Comment by stevesong** [comment]
Can confirm that this solves the problem for me.

**Comment by FiloSottile** [comment]
Thanks everyone for figuring this out even if I didn't have time to look into it!

I'd be happy to accept a PR fixing it

**Comment by RubenVerborgh** [comment]
Not that it really matters probably, but #4 correctly escapes the URL.
